apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${APP_NAME}
  namespace: lustre
  labels:
      app: ${APP_NAME}
spec:
  selector:
    matchLabels:
      name: ${APP_NAME}
  serviceName: ${APP_NAME}
  replicas: 1
  template:
    metadata:
      labels:
        name: ${APP_NAME}
    spec:
      hostNetwork: true
      nodeSelector:
        ${NODE_LABEL}: ""
      initContainers:
      - name: lustre-install
        image: kvaps/lustre-install
        env:
        - name: CHROOT
          value: "/host-root"
        volumeMounts:
        - name: host-root
          mountPath: "/host-root"
      containers:
      - name: ${APP_NAME}
        image: kvaps/lustre
        securityContext:
          privileged: true
        env:
        - name: CHROOT
          value: "/host-root"
        - name: HA_BACKEND
          value: "${LUSTRE_HA_BACKEND}"
        - name: RESOURCE_NAME
          value: "${APP_NAME}"
        - name: DEVICE
          value: "${LUSTRE_DEVICE}"
        - name: FSNAME
          value: "${LUSTRE_FSNAME}"
        - name: INDEX
          value: "${LUSTRE_INDEX}"
        - name: TYPE
          value: "${LUSTRE_TYPE}"
        - name: MGSNODE
          value: "${LUSTRE_MGSNODE}"
        - name: SERVICENODE
          value: "${LUSTRE_SERVICENODE}"
        volumeMounts:
        - name: host-root
          mountPath: /host-root
      terminationGracePeriodSeconds: 60
      volumes:
      - name: host-root
        hostPath:
          path: /
