apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${APP_NAME}-zfs
  namespace: lustre
  labels:
      app: ${APP_NAME}-zfs
spec:
  selector:
    matchLabels:
      name: ${NODE_LABEL}
  template:
    metadata:
      labels:
        name: ${APP_NAME}-zfs
    spec:
      initContainers:
      - name: lustre-install
        image: kvaps/drbd-install
        env:
        - name: CHROOT
          value: /host-root
        volumeMounts:
        - name: host-path
          mountPath: /host-path
      containers:
      - name: ${APP_NAME}-zfs
        image: kvaps/lustre
        securityContext:
          privileged: true
        env:
        - name: CHROOT
          value: /host-root
        - name: HA_BACKEND
          value: ${LUSTRE_HA_BACKEND}
        - name: RESOURCE_NAME
          value: ${APP_NAME}
        - name: DEVICE
          value: ${LUSTRE_DEVICE}
        - name: FSNAME
          value: ${LUSTRE_FSNAME}
        - name: TYPE
          value: ${LUSTRE_TYPE}
        - name: MGSNODE
          value: ${LUSTRE_MGSNODE}
        - name: SERVICENODE
          value: ${LUSTRE_SERVICENODE}
        volumeMounts:
        - name: host-path
          mountPath: /host-path
      terminationGracePeriodSeconds: 10
      volumes:
      - name: host-path
        hostPath:
          path: /
