apiVersion: batch/v1
kind: Job
metadata:
  name: kube-lustre-configurator
  namespace: lustre
spec:
  backoffLimit: 0
  template:
    spec:
      hostNetwork: true
      containers:
        - name: kube-lustre-configurator
          image: kvaps/kube-lustre-configurator
          volumeMounts:
          - name: config
            mountPath: /etc/kube-lustre
      volumes:
        - name: config
          configMap:
            name: kube-lustre-config
      restartPolicy: Never
